SELECT ?human ?humanLabel ?humanDescription ?gender ?birthdate ?deathdate ?nationality ?nationalityLabel
WHERE {
  {
    SELECT ?human ?humanDescription ?gender ?birthdate ?deathdate ?nationality
    WHERE {
      ?human
             # who has nationality(wdt:P27) [located in(wdt:P706) Korean Peninsula(Q483134) ] ;
             wdt:P27 [wdt:P706 wd:Q483134 ] ;
             wdt:P27 ?nationality ;
             wdt:P569 ?birthdate .
      OPTIONAL { ?human wdt:P21 ?gender . }
      OPTIONAL { ?human wdt:P570 ?deathdate . }
    }
  }
  SERVICE wikibase:label { bd:serviceParam wikibase:language "ko,en" . }
}