SELECT
  ?human ?humanLabel
  ?gender ?genderLabel
  ?birthdate
  ?deathdate
  ?nationality ?nationalityLabel
  ?invReltype ?invReltypeLabel
  ?relative
WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "ko,en" . }

  ?relative wdt:P31 wd:Q5 ;
            wdt:P27 [wdt:P706 wd:Q483134 ] ;
            ?invReltype ?human .

  OPTIONAL { ?human wdt:P21 ?gender . }
  OPTIONAL { ?human wdt:P569 ?birthdate . }
  OPTIONAL { ?human wdt:P570 ?deathdate . }
  OPTIONAL { ?human wdt:P27 ?nationality . }

  FILTER(?invReltype in (wdt:P22,wdt:P25,wdt:P26,wdt:P40,wdt:P3373))
}